sudo: required
services:
  - docker

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build
  - cargo doc --no-deps
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    echo "Testing branch '$TRAVIS_BRANCH'";
    docker run --rm -it archlinux/base sh -c "pacman -Syu --noconfirm >/dev/null 2>/dev/null && pacman -S --noconfirm git cargo clang hdf5 && mkdir build && cd build && git clone --branch '$TRAVIS_BRANCH' https://github.com/dns2utf8/alpm-rs.git && cd alpm-rs && cargo test" ;
    fi
notifications:
  on_success: change
  on_failure: always
  skip_join: true

